version: "3.4"

services:

  db:
    image: "postgres:15.5-alpine"
    container_name: "plc_data_platform_db"
    env_file:         # Loads PostgresSQL-required environment variables
      - ./backend/envs/dev.env
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - plc_data_platform_web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "plc_data_platform_backend:dev"
    container_name: "plc_data_platform_backend"
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/usr/src/backend
    depends_on:
    - db
    networks:
    - plc_data_platform_web

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: "plc_data_platform_proxy:dev"
    container_name: "plc_data_platform_proxy"
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - plc_data_platform_web

  siemens1:
    platform: "linux/x86_64"
    build:
      context: ./siemens1
      dockerfile: Dockerfile
    image: "plc_data_platform_siemens1:dev"
    container_name: "plc_data_platform_siemens1"
    volumes:
      - "./siemens1:/usr/src/siemens1"
    ports:
      - "102:102"
    networks:
      - plc_data_platform_web

networks:
  plc_data_platform_web:
    driver: bridge


volumes:
  db_volume:
